import type { ProtocolBlockConfig } from './protocol-types';

export const firstPageBlockConfigs: ProtocolBlockConfig[] = [
  {
    id: 'general',
    title: 'Общие данные о трансфузии',
    size: 'large',
    fields: [
      { name: 'recipientName', label: 'Фамилия, имя, отчество реципиента', wide: true },
      { name: 'requestDateTime', label: 'Дата и время подачи заявки', type: 'datetime-local' },
      { name: 'transfusionDate', label: 'Дата трансфузии', type: 'date' },
      { name: 'department', label: 'Отделение' },
      { name: 'medicalRecordNumber', label: '№ медицинской карты' },
      { name: 'startTime', label: 'Время начала трансфузии', type: 'time' },
      { name: 'endTime', label: 'Время окончания трансфузии', type: 'time' },
    ],
  },
  {
    id: 'examination',
    title: 'Данные медицинского обследования реципиента',
    size: 'medium',
    fields: [
      {
        name: 'recipientAbo',
        label: 'Группа крови AB0',
        type: 'select',
        options: ['O(I)', 'A(II)', 'B(III)', 'AB(IV)'],
      },
      {
        name: 'recipientRh',
        label: 'Резус-принадлежность',
        type: 'select',
        options: ['Rh(D)+', 'Rh(D)-'],
      },
      { name: 'recipientAntigenC', label: 'C (RH2)', type: 'select' },
      { name: 'recipientAntigenc', label: 'c (RH4)', type: 'select' },
      { name: 'recipientAntigenCw', label: 'Cʷ (RH8)', type: 'select' },
      { name: 'recipientAntigenE', label: 'E (RH3)', type: 'select' },
      { name: 'recipientAntigene', label: 'e (RH5)', type: 'select' },
      { name: 'recipientAntigenK', label: 'K (KEL1; Kell)', type: 'select' },
      { name: 'recipientAntigenk', label: 'k (KEL2; Cellano)', type: 'select' },
      { name: 'alloimmuneAntibodyStatus', label: 'Аллоиммунные антитела' },
      { name: 'alloimmuneAntibodyDescription', label: 'Описание антител', type: 'textarea' },
    ],
  },
  {
    id: 'indications',
    title: 'Показания к трансфузии',
    size: 'large',
    fields: [
      { name: 'indications', label: 'indications' },
      { name: 'indicationComponent', label: 'indicationComponent' },
      { name: 'indicationBloodLoss', label: 'indicationBloodLoss' },
      { name: 'indicationBloodLossPercent', label: 'indicationBloodLossPercent' },
      { name: 'indicationOngoingBleeding', label: 'indicationOngoingBleeding' },
      {
        name: 'indicationRbcCirculatoryDisturbances',
        label: 'indicationRbcCirculatoryDisturbances',
      },
      { name: 'indicationRbcHemicHypoxia', label: 'indicationRbcHemicHypoxia' },
      { name: 'indicationRbcThreshold', label: 'indicationRbcThreshold' },
      { name: 'indicationRbcHgb', label: 'indicationRbcHgb' },
      { name: 'indicationRbcHct', label: 'indicationRbcHct' },
      { name: 'indicationRbcOther', label: 'indicationRbcOther' },
      { name: 'indicationRbcOtherText', label: 'indicationRbcOtherText' },
      { name: 'indicationPlasmaFactorDeficiency', label: 'indicationPlasmaFactorDeficiency' },
      { name: 'indicationPlasmaAnticoagulantOverdose', label: 'indicationPlasmaAnticoagulantOverdose' },
      { name: 'indicationPlasmaPlasmapheresis', label: 'indicationPlasmaPlasmapheresis' },
      { name: 'indicationPlasmaOther', label: 'indicationPlasmaOther' },
      { name: 'indicationPlasmaOtherText', label: 'indicationPlasmaOtherText' },
      { name: 'indicationPlateletReason', label: 'indicationPlateletReason' },
      { name: 'indicationPlateletOther', label: 'indicationPlateletOther' },
      { name: 'indicationPlateletOtherText', label: 'indicationPlateletOtherText' },
    ],
  },
  {
    id: 'history',
    title: 'Анамнез реципиента',
    size: 'large',
    fields: [
      {
        name: 'previousTransfusions',
        label: 'Трансфузии компонентов крови в анамнезе',
        type: 'textarea',
        wide: true,
      },
      {
        name: 'previousReactions',
        label: 'Реакции и осложнения на трансфузии в анамнезе',
        type: 'textarea',
        wide: true,
      },
      {
        name: 'individualSelectionHistory',
        label: 'Трансфузии по индивидуальному подбору',
        type: 'textarea',
        wide: true,
      },
    ],
  },
  {
    id: 'donor',
    title: 'Данные о донорской крови или ее компоненте',
    size: 'xlarge',
    fields: [
      { name: 'componentName', label: 'Наименование компонента донорской крови', wide: true },
      { name: 'collectionOrganization', label: 'Организация, осуществившая заготовку', wide: true },
      {
        name: 'donorAbo',
        label: 'Группа крови донора AB0',
        type: 'select',
        options: ['O(I)', 'A(II)', 'B(III)', 'AB(IV)'],
      },
      { name: 'donorAntigens', label: 'Антигены эритроцитов донора C, c, E, e, K' },
      { name: 'componentUnitNumber', label: '№ единицы компонента крови' },
      { name: 'amountMl', label: 'Количество, мл', type: 'number', step: '1' },
      { name: 'collectionDate', label: 'Дата заготовки', type: 'date' },
      { name: 'expirationDate', label: 'Срок годности', type: 'date' },
    ],
  },
];
